### ISSUE TITLE
Add language:key command

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-console-joomlatools#1]
Add language:key command to generate language keys from given strings. 

Example
``` 
$ joomla language:key test foo -v
KLS_FOO
```

**Comment by ercanozkaya** [comment]
To test:
Run this command in the Vagrant box
```
joomla plugin:install joomlatools/joomla-console-joomlatools:dev-master
```

And then test if it works by:
```
joomla language:key test "Document image link to"
```

**Comment by rmdstudio** [comment]
@ercanozkaya when I run the first command I get 

```joomlatools/joomla-console-joomlatools:dev-master is not a Joomla console plugin```
```Plugin not installed```

how do I install `joomlatools/joomla-console-joomlatools` ?

**Comment by johanjanssens** [comment]
@stevenrombauts Can you help Rastin here ? If I understand it right this plugin is installed in the latest version of the box ?

**Comment by stevenrombauts** [comment]
@rmdstudio The test commands have changed since Ercan posted them since we renamed the plugin to `joomlatools/console-joomlatools`. The first command is now:

```
joomla plugin:install joomlatools/console-joomlatools
```

Although if you updated to the latest box it should already be included (including the language:key command)!
